FROM base/archlinux

ENV PATH $PATH:/root/.gem/ruby/2.4.0/bin

# Install dependencies
RUN pacman -Sy --noconfirm archlinux-keyring
RUN pacman -Syu --noconfirm git gcc make curl base-devel gdbm openssl libffi doxygen graphviz libyaml ttf-dejavu tk gdbm openssl libffi libyaml gmp zlib readline ruby

# Install fpm
RUN gem install --no-ri --no-rdoc fpm