#!/bin/bash

docker build --no-cache -t mac-installer -f Dockerfile.mac-bundle .
CONTAINER="$(docker run -d mac-installer)"
mkdir -p dist/mac
docker cp "${CONTAINER}":/NanoboxBundle.pkg dist/mac/
docker rm "${CONTAINER}" 2>/dev/null || true
