#!/bin/sh

set -e

docker build --no-cache -t windows-installer -f Dockerfile.windows .
CONTAINER="$(docker run -d windows-installer)"
mkdir -p dist/windows
docker cp "${CONTAINER}":/installer/Output/NanoboxSetup.exe dist/windows/
# docker cp "${CONTAINER}":/installer/Output/NanoboxSetup-signed.exe dist/
docker rm "${CONTAINER}" 2>/dev/null || true
